-- Push subscriptions do cliente final (Web Push Protocol).
--
-- Cada device do mesmo cliente gera um endpoint diferente. UNIQUE(customer_id, endpoint)
-- evita rows duplicadas se o cliente reinscrever no mesmo device.
--
-- Quando o navegador/SO invalida a subscription (usuario apagou app, revogou
-- permissao, etc), retornos 404/410 do servidor de push disparam delete da row.

CREATE TABLE IF NOT EXISTS ops.push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    endpoint TEXT NOT NULL,
    p256dh VARCHAR(255) NOT NULL,
    auth VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_push_sub_customer
        FOREIGN KEY (customer_id) REFERENCES fidelity.customers(id),
    CONSTRAINT uq_push_sub_customer_endpoint
        UNIQUE (customer_id, endpoint)
);

CREATE INDEX IF NOT EXISTS idx_push_sub_customer
    ON ops.push_subscriptions (customer_id);
