-- SCHEMAS
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS fidelity;
CREATE SCHEMA IF NOT EXISTS ops;

-- =========================
-- CORE
-- =========================
CREATE TABLE core.merchants (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(120) NOT NULL,
  document     VARCHAR(20),
  active       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE core.locations (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id  BIGINT NOT NULL REFERENCES core.merchants(id),
  name         VARCHAR(120) NOT NULL,
  address      VARCHAR(255),
  flags        JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_locations_merchant_id ON core.locations(merchant_id);
CREATE INDEX IF NOT EXISTS idx_locations_flags_gin ON core.locations USING GIN (flags);

CREATE TABLE core.staff_users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id   BIGINT NOT NULL REFERENCES core.merchants(id),
  email         VARCHAR(160) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role          VARCHAR(20) NOT NULL, -- ADMIN | CASHIER
  active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================
-- FIDELITY
-- =========================
CREATE TABLE fidelity.programs (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id       BIGINT NOT NULL REFERENCES core.merchants(id),
  name              VARCHAR(120) NOT NULL,
  rule_total_stamps INT NOT NULL DEFAULT 10,
  reward_name       VARCHAR(120) NOT NULL DEFAULT 'Refeição grátis',
  expiration_days   INT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_programs_merchant_id ON fidelity.programs(merchant_id);

CREATE TABLE fidelity.customers (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email       VARCHAR(160),
  phone       VARCHAR(30),
  provider_id VARCHAR(80),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE fidelity.cards (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id   BIGINT NOT NULL REFERENCES fidelity.programs(id),
  customer_id  BIGINT NOT NULL REFERENCES fidelity.customers(id),
  stamps_count INT NOT NULL DEFAULT 0,
  status       VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE | BLOCKED | EXPIRED
  expires_at   TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_cards_program_customer UNIQUE (program_id, customer_id)
);
CREATE INDEX IF NOT EXISTS idx_cards_program_id ON fidelity.cards(program_id);
CREATE INDEX IF NOT EXISTS idx_cards_customer_id ON fidelity.cards(customer_id);

CREATE TABLE fidelity.stamps (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id     BIGINT NOT NULL REFERENCES fidelity.cards(id),
  when_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  location_id BIGINT REFERENCES core.locations(id),
  cashier_id  BIGINT REFERENCES core.staff_users(id),
  source      CHAR(1) NOT NULL, -- 'A' (CUSTOMER_QR) | 'B' (STORE_QR)
  token_id    BIGINT,
  ip          INET,
  user_agent  TEXT
);
CREATE INDEX IF NOT EXISTS idx_stamps_card_when ON fidelity.stamps(card_id, when_at);

CREATE TABLE fidelity.rewards (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id     BIGINT NOT NULL REFERENCES fidelity.cards(id),
  issued_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  redeemed_at TIMESTAMPTZ,
  location_id BIGINT REFERENCES core.locations(id),
  cashier_id  BIGINT REFERENCES core.staff_users(id)
);
CREATE INDEX IF NOT EXISTS idx_rewards_card_id ON fidelity.rewards(card_id);

-- =========================
-- OPS (tokens efêmeros / anti-replay)
-- =========================
CREATE TABLE ops.stamp_tokens (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type      VARCHAR(20) NOT NULL, -- CUSTOMER_QR | STORE_QR
  id_ref    BIGINT NOT NULL,      -- card_id (A) OU location_id (B)
  nonce     UUID NOT NULL UNIQUE,  -- anti-replay
  exp_at    TIMESTAMPTZ NOT NULL,
  used_at   TIMESTAMPTZ,
  signature TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_stamp_tokens_id_ref ON ops.stamp_tokens(id_ref);
