-- Refresh tokens para staff (opaque, longa vida, rotativos).
--
-- O cliente recebe o `token` aleatorio (UUID base64url ou similar). Apenas o
-- hash SHA-256 e armazenado aqui — comprometer o banco nao expoe os tokens.
--
-- Rotacao: cada uso do refresh emite um token novo e marca o antigo como
-- `revoked_at = NOW()`, com `replaced_by_id` apontando para o sucessor. Isso
-- permite detectar reuso de token antigo (sinal de comprometimento) — embora
-- a reacao a isso (revogar a familia inteira) seja Tier 4.

CREATE TABLE IF NOT EXISTS ops.refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    staff_user_id BIGINT NOT NULL,
    merchant_id BIGINT NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    replaced_by_id BIGINT,
    ip INET,
    user_agent TEXT,

    CONSTRAINT fk_refresh_tokens_staff
        FOREIGN KEY (staff_user_id) REFERENCES core.staff_users(id),
    CONSTRAINT fk_refresh_tokens_merchant
        FOREIGN KEY (merchant_id) REFERENCES core.merchants(id),
    CONSTRAINT fk_refresh_tokens_replaced_by
        FOREIGN KEY (replaced_by_id) REFERENCES ops.refresh_tokens(id)
);

-- Index para o lookup do refresh (hash UNIQUE ja indexa, mas explicito):
-- Procurar tokens ativos por staff (logout, listar sessoes ativas futuro):
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_staff_active
    ON ops.refresh_tokens (staff_user_id)
    WHERE revoked_at IS NULL;
