-- @Version no Card
ALTER TABLE fidelity.cards
  ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

-- (opcional) remove default depois que todos os registros tiverem valor
-- ALTER TABLE fidelity.cards ALTER COLUMN version DROP DEFAULT;

-- Idempotency (se não existir)
CREATE TABLE IF NOT EXISTS ops.idempotency_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key VARCHAR(80) UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);