-- Tokens de reset de senha para staff (opaque, one-shot, TTL curto).
--
-- Mesmo padrao dos refresh_tokens: armazenamos apenas o hash SHA-256.
-- Token e consumido (`used_at = NOW()`) na primeira utilizacao bem-sucedida.
-- Apos consumir, fica historico imutavel para audit.

CREATE TABLE IF NOT EXISTS ops.password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    staff_user_id BIGINT NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    ip INET,
    user_agent TEXT,

    CONSTRAINT fk_password_reset_staff
        FOREIGN KEY (staff_user_id) REFERENCES core.staff_users(id)
);

-- Index parcial para "tokens ativos por staff" (nao consumidos):
CREATE INDEX IF NOT EXISTS idx_password_reset_staff_active
    ON ops.password_reset_tokens (staff_user_id)
    WHERE used_at IS NULL;
