-- Tabela associativa: staff_user pode operar em varios merchants
CREATE TABLE core.staff_user_merchants (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_user_id BIGINT NOT NULL REFERENCES core.staff_users(id),
  merchant_id   BIGINT NOT NULL REFERENCES core.merchants(id),
  role          VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN','CASHIER')),
  active        BOOLEAN NOT NULL DEFAULT TRUE,
  is_default    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_staff_merchant UNIQUE (staff_user_id, merchant_id)
);

CREATE INDEX idx_sum_staff_user ON core.staff_user_merchants(staff_user_id);
CREATE INDEX idx_sum_merchant   ON core.staff_user_merchants(merchant_id);

-- Migrar dados existentes de staff_users para a tabela associativa
INSERT INTO core.staff_user_merchants (staff_user_id, merchant_id, role, is_default)
SELECT id, merchant_id, role, TRUE
FROM core.staff_users;

-- Remover check constraint de role em staff_users
ALTER TABLE core.staff_users DROP CONSTRAINT IF EXISTS ck_staff_role;

-- Remover coluna merchant_id (FK inline tem nome auto-gerado)
ALTER TABLE core.staff_users DROP COLUMN merchant_id;

-- Remover coluna role
ALTER TABLE core.staff_users DROP COLUMN role;
