-- Audit log de acoes criticas do sistema.
-- Schema `ops` (operacional/transient/observability, mesmo schema de
-- stamp_tokens e idempotency_keys).
--
-- Estrutura propositadamente "wide" para flexibilidade:
--  - actor_type/actor_id: quem fez (STAFF, CUSTOMER ou SYSTEM).
--  - action: enum textual (LOGIN_SUCCESS, STAMP_APPLIED, etc.).
--  - entity_type/entity_id: opcional, do que se trata.
--  - merchant_id: opcional, contexto multi-tenant.
--  - details: JSONB livre para campos especificos da acao.
--  - success: para acoes que tem resultado binario (login).

CREATE TABLE IF NOT EXISTS ops.audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actor_type VARCHAR(20) NOT NULL,
    actor_id BIGINT,
    action VARCHAR(60) NOT NULL,
    entity_type VARCHAR(40),
    entity_id BIGINT,
    merchant_id BIGINT,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    details JSONB DEFAULT '{}'::jsonb,
    ip INET,
    user_agent TEXT,

    CONSTRAINT chk_audit_actor_type CHECK (actor_type IN ('STAFF', 'CUSTOMER', 'SYSTEM', 'ANONYMOUS'))
);

-- Indices para queries de investigacao mais comuns:
CREATE INDEX IF NOT EXISTS idx_audit_occurred_at_desc
    ON ops.audit_log (occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_merchant_action_occurred
    ON ops.audit_log (merchant_id, action, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_actor
    ON ops.audit_log (actor_type, actor_id, occurred_at DESC);
